FROM nginx:1.21.3

COPY ./dist /dist

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

#FROM node:14-alpine
#
#WORKDIR /app 
#
#COPY . /app
#
#RUN cd /app && npm install 
#
#
#CMD ["npm", "run", "prod"]


